runtime: nodejs16 

instance_class: F2

env_variables:
  BUCKET_NAME: ""
  PORT: 3000
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  POSTGRES_USER: post_sm_gres
  POSTGRES_DATABASE: OCXCRM
  POSTGRES_PASSWORD: 1234
  
handlers:
- url: /api/v1/
  static_dir: dist

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto